#cloud-config
vyos_config_commands:
  - set system host-name 'vyos-test'
#  - set interfaces ethernet eth2 address dhcp
#  - set interfaces ethernet eth2 description 'WAN'
#  - set interfaces ethernet eth3 address '10.10.1.1/24'
#  - set interfaces ethernet eth3 description 'LAN'
#  - set system name-server '8.8.8.8'
#  - set nat source rule 100 outbound-interface 'eth2'
#  - set nat source rule 100 source address '10.10.1.0/24'
#  - set nat source rule 100 translation address masquerade 
#  - set service dhcp-server shared-network-name 'LAN' authoritative 
#  - set service dhcp-server shared-network-name 'LAN' subnet '10.10.1.0/24' default-router '10.10.1.1'
#  - set service dhcp-server shared-network-name 'LAN' subnet '10.10.1.0/24' domain-name '10.10.1.1'
#  - set service dhcp-server shared-network-name 'LAN' subnet '10.10.1.0/24' lease 1800
#  - set service dhcp-server shared-network-name 'LAN' subnet '10.10.1.0/24' range '0' start '10.10.1.100'
#  - set service dhcp-server shared-network-name 'LAN' subnet '10.10.1.0/24' range '0' stop '10.10.1.200'
#  - set service dns forwarding system
#  - set service dns forwarding listen-address '10.10.1.1'
#  - set service dns forwarding allow-from '10.10.1.0/24'
#  - set system login user vyos authentication public-keys vykey type ssh-rsa
#  - set system login user vyos authentication public-keys vykey key 'AAAAB3NzaC1yc2EAAAADAQABAAACAQC4ClQ5snQsfCcafk5Lfgcv7EzGkChwbRSFiRJqKeEZ/VFhhrpLDOn12ZPoKi/uOk9EMuWoZ2R6yaO/YW2R8c4o/GpIlb824BSfE7xKw8QHQgOzcKGMs0QVsYGY5NKEXwQ7OaR6QiX7+lZxn4B/AbXvqJT9PGhxC9KUMoXtdWy3pDWsv9bPl+V5SgJqCZr2vhQTF3Q0d4TSThaZDVkrXzkNKfxAz/+MXhGwt4BteeD3miL7W2XiEKj/NEWXnv/9DxvlJcutyn1QV7EzAjjJsEgxgcniHetEz5UO4AH9dEGQ7z9ufm2bLLLPGDjO67inhs5VOuiDY/1oQN/XlImqK/mVVB6/X/HwNv/sQTqKwXERDYvXrdzcO+ZGW67oEnPaVhzGuIL6qAK8lbuApRuPWQ2mB8r6ckUb4DCEfdEwumaHnhyqwFw7FGSCCWpsj8CsgM2GN6fWfJBnRknBaII3OXa3/eiOF1xibQZ2cGxZvceoJHZSqSE8dE5OeRT64y6JqlC9i+D8wrRfAeu3LIesw8csXm7KpiH5b5140KUHFSMxdPBj7rVOvaJK0BpMN87fav8RKObEGlhNfvUK3/kTF8PvG7vXoy9RglO3a7pSNMTNgsZ8DqV/MR1JVTgIxlJrmJpFt00KF2VEpneYT0nlyy6JPlj9gW/exc+9mBowuov1PQ=='
